import type { Metadata } from 'next';

import { getAppTitle } from '@/shared/utils';

export const metadata: Metadata = {
	title: getAppTitle('main'),
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <>{children}</>;
}
