import './globals.css';
import type { Metadata } from 'next';
import { StyledEngineProvider } from '@mui/material/styles';
import 'react-circular-progressbar/dist/styles.css';
import { inter } from './fonts';

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<StyledEngineProvider injectFirst>
				<body className={inter.className}>{children}</body>
			</StyledEngineProvider>
		</html>
	);
}
